name: CI
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  static-checks-and-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        poetry-version: ["2.1.3"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dev dependencies
        run: poetry install
      - name: Run linting
        run: poetry run black githublfs --check
      - name: Run type checking
        run: poetry run mypy githublfs --install-types --non-interactive --ignore-missing-imports
      - name: Run tests
        run: poetry run pytest
  push-to-pypi:
    needs:
      - static-checks-and-tests
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
            python-version: 3.12.0
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 2.1.3
      - name: Install
        run: poetry install
      - name: Build
        run: poetry build
      - name: check
        run: poetry run twine check dist/*
      - name: push to pypi
        run: poetry run twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
